version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-broker:
    image: confluentinc/cp-kafka
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: SSL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SSL_KEY_CREDENTIALS: kafka-broker.key
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-broker.key
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-broker.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: "eppunormaali"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-broker.key
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-broker.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "eppunormaali"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - "./ssl:/etc/kafka/secrets"
