version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper.mikkomulperi.fi
    container_name: zookeeper.mikkomulperi.fi
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-broker:
    image: confluentinc/cp-kafka
    hostname: kafka-broker.mikkomulperi.fi
    container_name: kafka-broker.mikkomulperi.fi
    mem_reservation: 4g
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka-broker.mikkomulperi.fi:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_KEY_CREDENTIALS: kafka-broker.key.credentials
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-broker.keystore.credentials
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-broker.keystore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-broker.truststore.credentials
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-broker.truststore.jks
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - "./ssl:/etc/kafka/secrets"
